# Generated by Django 6.0.7 on 2026-07-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analyzer",
            "0002_resume_ats_score_resume_candidate_name_resume_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="cover_letter",
            field=models.TextField(blank=True),
        ),
    ]
